import Head from "next/head";
import { FaBed, FaPlane, FaCar, FaTaxi } from "react-icons/fa";
// import Image from "next/image";
// import { Inter } from "@next/font/google";

// const inter = Inter({ subsets: ["latin"] });

import Header from "@/components/Layout/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Booking App UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {/* <section className="hero | u-bg-blue u-text-white">
          <div className="container">
            <div className="hero__list">
              <div className="hero__list-item active">
                <FaBed className="hero__list-icon" />
                <span>Stays</span>
              </div>
              <div className="hero__list-item">
                <FaPlane className="hero__list-icon" />
                <span>Flights</span>
              </div>
              <div className="hero__list-item">
                <FaCar className="hero__list-icon" />
                <span>Car Rentals</span>
              </div>
              <div className="hero__list-item">
                <FaBed className="hero__list-icon" />
                <span>Attractions</span>
              </div>
              <div className="hero__list-item">
                <FaTaxi className="hero__list-icon" />
                <span>Airport Taxis</span>
              </div>
            </div>
          </div>
          <div className="container">
            <h1 className="hero__tile">
              A lifetime of discounts? It&lsquo;s a genius
            </h1>

            <p className="hero__desc">
              Get rewarded for your travels - unlock instant savings of 10% or
              more with a free Lamabooking account
            </p>

            <button className="hero__btn | u-bg-blue-200 u-text-white">
              Sign In / Register
            </button>
          </div>
        </section> */}
      </main>
    </>
  );
}
