import Head from "next/head";
import { FaBed } from "react-icons/fa";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

import Header from "@/components/Layout/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Booking App UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <section className="hero">
          <div className="hero__list">
            <div className="hero__list-item">
              <FaBed className="hero__bed" />
            </div>
          </div>
        </section>
        <h1>Hello World</h1>
      </main>
    </>
  );
}
