import Head from "next/head";
import Header from "@/components/Layout/Header";
import Featured from "@/components/Section/Featured";

export default function Home() {
  return (
    <>
      <Head>
        <title>LHeude Bookings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="container">
          <Featured />
        </div>
      </main>
    </>
  );
}
